services:
    arthem_graphql.mapping.driver.yaml:
        public: false
        abstract: true
        class: Arthem\GraphQLMapper\Mapping\Driver\YamlDriver

    arthem_graphql.factory.type_resolver:
        public: false
        class: Arthem\GraphQLMapper\Schema\TypeResolver

    arthem_graphql.schema_factory:
        public: false
        class: Arthem\GraphQLMapper\Schema\SchemaFactory
        arguments:
            - @arthem_graphql.mapping.driver.yaml
            - @arthem_graphql.factory.type_resolver
            - @arthem_graphql.mapping.guesser
        calls:
            - [setCacheDriver, [@arthem_graphql.mapping.cache.file]]

    arthem_graphql.manager:
        class: Arthem\GraphQLMapper\GraphQLManager
        arguments:
            - @arthem_graphql.schema_factory
